### ISSUE TITLE
Geofence reporting not working on 3G network

### ISSUE THREAD

**Issue by sirghi** [tomtom-international/maps-sdk-for-ios-examples#4]
I'm using the SDK to determine whether a user is within a Geofence or not. It works ok on wi-fi, but when the phone is on a cellular network, the request fails with the following error:

    Error Domain=TTErrorDomain Code=401 "(null)" UserInfo={description=Query: report/<projecti_id>/?point=23.6454,56.9485&range=5000
    Err:{"message":"Configuration not found"}}

 I tried to extract some more info via Charles or other proxy tools, but this call is not detected by any of them. I don't know, maybe the SDK does some non-standard http requests.

In any case, if you can try it on your end, or if you have any other hints on how this can be fixed, will be very grateful.

**Comment by 7tomek** [comment]
Hi, Do you use an example ? or  Can you provide a sample of code which generates that issue?
Please update to the newest version of SDK.

**Comment by sirghi** [comment]
Hi, yes, I'm using the example project, nothing special I think:

    func requestGeofencingReport(coordinate: CLLocationCoordinate2D, projectId: String) {
        let reportQuery = TTGeofencingReportQueryBuilder(location: TTLocation(coordinate: coordinate))
            .withProject(projectId)
            .withRange(range).build()
        let service = TTGeofencingReportService()

        service.report(with: reportQuery) { (report, error) in
            if let err = error {
                let alert = UIAlertController(title: "Error", message: err.localizedDescription, preferredStyle: .alert)
                let cancel = UIAlertAction(title: "OK", style: .cancel, handler: nil)
                alert.addAction(cancel)
                self.present(alert, animated: true, completion: nil)
            } else {
                self.responseGeofencing(report: report)
            }
        }
    }

**Comment by 7tomek** [comment]
Ok, so please use your web browser and fill this data and try request on wi-fi and 3G
https://api.tomtom.com/geofencing/1/report/<project_id>/?point=4.90947,52.3773&range=5000&key=<geofencing_key>

**Comment by sirghi** [comment]
Hi @7tomek, I tried it and it works both on wi-fi and 3G. So I wonder why doesn't it work in the App. Did you try the example project on 3G?

**Comment by sirghi** [comment]
@7tomek, any updates?
It's kind of a blocker for us

**Comment by 7tomek** [comment]
@sirghi We launched Maps SDK Samples at 3g / LTE and we have no issue. We need to look at the problem closer. We have a planned task for this problem and we will solve it as soon as possible. We'll let you know in the near future.

**Comment by sirghi** [comment]
Thanks, appreciate it.

Pe 11 iul. 2019, la 16:22, Tomek <notifications@github.com> a scris:

**Comment by sirghi** [comment]
Hi, any news about it?

**Comment by kwawrzyniak** [comment]
Hi @sirghi we take a closer look at your issue and found potential cause of it. 
We think the problem is connected with wrong project configuration - You probably using your API Key with PROJECT ID obtained from example app. 
please make sure you followed all steps described here:
https://developer.tomtom.com/maps-sdk-ios/report-service
1. You need to create register admin key:
`curl -v -XPOST -H "Content-type: application/json" -d '{ "secret": "TYPE HERE WHAT EVER YOU WANT AND KEEP IT SECRET" }' https://api.tomtom.com/geofencing/1/register?key=YOUR_API_KEY`
It shall return 
`{
"adminKey": "YOUR ADMIN KEY WILL BE HERE"
}`
2. With your admin key you will be able to create new project.
`curl -v -XPOST -H "Content-type: application/json" -d '{"name": "NAME YOUR PROJECT HERE"}' 'https://api.tomtom.com/geofencing/1/projects/project?key=YOUR_API_KEY&adminKey=YOUR_ADMIN_KEY'`
It shall return:
`{
"id": "ID-OF-A-PROJECT"
"name": "NAME YOUR PROJECT HERE"
}`
3. Having project you shall be able to add new fence using:
`curl -XPOST -H "Content-type: application/json" -d '{
"name": "tom tom",
"type": "Feature",
"geometry": {
"radius": 10, //in meters
"type": "Point",
"shapeType": "Circle",
"coordinates": [51.759338, 19.448624]
}
}' 'https://api.tomtom.com/geofencing/1/projects/YOUR_PROJECT_ID/fence?key=YOUR_API_KEY&adminKey=YOUR_ADMIN_KEY'`

Doing all of this steps above you shall now be able to create report for given lat/lng.

**Comment by sirghi** [comment]
Hi @kwawrzyniak, I have done the above steps. Otherwise it wouldn't have worked on wi-fi. And like I said, on wi-fi it works ok. On 3G the above problem appears.
Can you confirm whether you used the demo app on a real device using 3G please?

**Comment by kwawrzyniak** [comment]
Hi, @sirghi yes, we checked this on 3G and wifi and on both works perfectly. Can you please create new account on https://developer.tomtom.com and using new credentials re-setup your example project and share it here?

**Comment by sirghi** [comment]
Embarrassing as it is, but the problem was that, in GeofencingReportViewController,  I was always creating a new TTGeofencingReportService for some reason, when pressing the report button. Probably it hit an edge case when it wasn't able to initialize itself properly before making the request on 3G. Removing that and keeping the Reporting Service that was created in viewDidLoad fixed it.

Apologies for the false alarm.
