### ISSUE TITLE
On TTMapView,userLocation NO work,  reture 0

### ISSUE THREAD

**Issue by liang-21** [tomtom-international/maps-sdk-for-ios-examples#5]

**Comment by liangshiweiweb** [comment]
in onMapReadyCompletion,i already set showsUserLocation was Yes

**Comment by kwawrzyniak** [comment]
Hi @liangshiweiweb 

If you are using TomTomSDKExamples, you probably don't see your location pin because Xcode sets your location to London. To disable location situation please select MapsSDKExampleObj or MapsSDKExampleSwift schema and:

- select EDIT given schema,
- go to Options tab
- deselect Allow Location Simulation
